In [1]:
import numpy as np

#Funciones dadas en clase que se usarán

In [2]:
def SolverDiagonal(A, b):
    """
    Resuelve un sistema de ecuaciones lineales donde la matriz A es diagonal.

    Esta función resuelve el sistema de ecuaciones Ax = b, donde A es una matriz diagonal
    representada por su diagonal principal (un vector). La solución se obtiene dividiendo
    cada elemento del vector b por el correspondiente elemento de la diagonal de A.

    Parámetros:
    -----------
    A : array_like
        Un arreglo unidimensional que representa la diagonal principal de la matriz A.
        Debe tener la misma longitud que el vector b.

    b : array_like
        Un arreglo unidimensional que representa el vector de términos independientes del sistema.

    Retorna:
    --------
    x : ndarray
        Un arreglo unidimensional que contiene la solución del sistema Ax = b.

    Ejemplo:
    --------
    >>> A = np.array([2, 4, 6])  # Diagonal principal de la matriz A
    >>> b = np.array([8, 16, 36])  # Vector de términos independientes
    >>> x = SolverDiagonal(A, b)
    >>> print(x)
    [4. 4. 6.]

    Notas:
    ------
    - La función asume que la matriz A es diagonal y que no hay elementos fuera de la diagonal.
    - Si algún elemento de la diagonal A es cero, se producirá un error de división por cero.
    """
    n = len(A)
    x = np.zeros_like(A, dtype=float)  # Asegura que x sea de tipo flotante
    for i in range(n):
        x[i] = b[i] / A[i]
    return x

In [3]:
def SustitucionDelante(Mat, b):
    """
    Realiza la sustitución hacia adelante para resolver un sistema de ecuaciones lineales
    representado por una matriz triangular inferior.

    Parámetros:
    -----------
    Mat : numpy.ndarray
        Una matriz triangular inferior de tamaño n x n.
    b : numpy.ndarray
        Un vector de términos independientes de tamaño n.

    Retorna:
    --------
    x : numpy.ndarray
        Un vector solución de tamaño n que satisface la ecuación Mat @ x = b.

    Descripción:
    ------------
    Esta función resuelve un sistema de ecuaciones lineales de la forma Mat @ x = b,
    donde Mat es una matriz triangular inferior. Utiliza el método de sustitución hacia adelante,
    comenzando desde la primera fila de la matriz y avanzando hacia la última.

    Ejemplo:
    --------
    >>> Mat = np.array([[1, 0, 0],
    ...                 [2, 3, 0],
    ...                 [4, 5, 6]])
    >>> b = np.array([1, 8, 32])
    >>> SustitucionDelante(Mat, b)
    array([1., 2., 3.])
    """
    n = Mat.shape[0]
    x = np.zeros(n)

    for i in range(n):
        SumCum = 0.0
        for j in range(i):
            SumCum += Mat[i, j] * x[j]
        x[i] = (b[i] - SumCum) / Mat[i, i]

    return x

In [4]:
def SustitucionAtras(Mat, b):
    """
    Realiza la sustitución hacia atrás para resolver un sistema de ecuaciones lineales
    representado por una matriz triangular superior.

    Parámetros:
    -----------
    Mat : numpy.ndarray
        Una matriz triangular superior de tamaño n x n.
    b : numpy.ndarray
        Un vector de términos independientes de tamaño n.

    Retorna:
    --------
    x : numpy.ndarray
        Un vector solución de tamaño n que satisface la ecuación Mat @ x = b.

    Descripción:
    ------------
    Esta función resuelve un sistema de ecuaciones lineales de la forma Mat @ x = b,
    donde Mat es una matriz triangular superior. Utiliza el método de sustitución hacia atrás,
    comenzando desde la última fila de la matriz y avanzando hacia la primera.

    Ejemplo:
    --------
    >>> Mat = np.array([[3, 2, 1],
    ...                 [0, 2, 1],
    ...                 [0, 0, 1]])
    >>> b = np.array([6, 4, 1])
    >>> SustitucionAtras(Mat, b)
    array([1., 1., 1.])
    """
    n = Mat.shape[0]
    x = np.zeros(n)

    for i in range(n-1, -1, -1):
        SumCum = 0.0
        for j in range(i+1, n):
            SumCum += Mat[i, j] * x[j]
        x[i] = (b[i] - SumCum) / Mat[i, i]

    return x

# Definimos la funcion SolveBanda
La función detecta el tipo de sistema

In [5]:
def SolveBanda(A, b):
    """
    Resuelve un sistema Ax = b para una matriz de dos bandas.

    La función detecta si la matriz A posee una banda superior o inferior:
      - Si A[0,1] es distinto de cero se asume que la banda adicional es superior,
        y se utiliza sustitución hacia atrás.
      - Si A[1,0] es distinto de cero se asume que la banda adicional es inferior,
        y se utiliza sustitución hacia adelante.
      - Si no se detecta banda adicional, se asume que la matriz es diagonal,
        y se resuelve dividiendo cada elemento de b por el correspondiente de la diagonal.

    Parámetros:
      A : numpy.ndarray
          Matriz de coeficientes (n x n).
      b : numpy.ndarray
          Vector de términos independientes (n).

    Retorna:
      numpy.ndarray
          Solución x del sistema Ax = b.
    """
    n = A.shape[0]
    if n > 1 and A[0, 1] != 0: #Verifica si se trata de un sistema de banda superior
        return SustitucionAtras(A, b)

    elif n > 1 and A[1, 0] != 0: #Verifica si se trata de un sistema de banda inferior
        return SustitucionDelante(A, b)

    else: #Caso en el que solo es la diagonal principal
        diag = np.diag(A)
        return SolverDiagonal(diag, b)

Hacemos uso de la funcion para resulver el sistema de dos bandas

In [6]:
# ------------------------
# MATRIZ CON BANDA SUPERIOR
# A = np.array([[4, 2, 0, 0],
#             [0, 3, 1, 0],
#             [0, 0, 5, 2],
#             [0, 0, 0, 6]])
# b = np.array([8, 7, 9, 5])
# ------------------------

# ------------------------
# MATRIZ CON BANDA INFERIOR.
A = np.array([[3, 0, 0, 0],
          [2, 4, 0, 0],
          [0, 1, 5, 0],
          [0, 0, 2, 6]])
b = np.array([5, 6, 7, 8])
# ------------------------

# Mostrar la matriz A y el vector b
print("Matriz A:")
print(A)
print("\nVector b:")
print(b)

# Resolver el sistema usando SolveBanda
try:
    x = SolveBanda(A, b)
    print("\nSolución del sistema Ax = b:")
    print(x)

    # Verificar la solución (se calcula A*x y se muestra)
    print("\nVerificación (A * x):")
    print(A @ x)

except Exception as e:
    print("Error al resolver el sistema:", e)


Matriz A:
[[3 0 0 0]
 [2 4 0 0]
 [0 1 5 0]
 [0 0 2 6]]

Vector b:
[5 6 7 8]

Solución del sistema Ax = b:
[1.66666667 0.66666667 1.26666667 0.91111111]

Verificación (A * x):
[5. 6. 7. 8.]
