In [1]:
import numpy as np
from numpy import linalg as LA

In [2]:
# Tamaño de la matriz
n = 5

# Crear la diagonal principal
DP = 2 * np.ones(n)
diagonal_principal = np.diag(DP)

# Crear la diagonal superior
DS = -np.ones(n - 1)
diagonal_superior = np.diag(DS, k=1)

# Crear la diagonal inferior
DI = -np.ones(n - 1)
diagonal_inferior = np.diag(DI, k=-1)

# Sumar las tres diagonales para obtener la matriz tribanda
matriz_tribanda = diagonal_principal + diagonal_superior + diagonal_inferior
print(matriz_tribanda)

b = np.ones(n)

[[ 2. -1.  0.  0.  0.]
 [-1.  2. -1.  0.  0.]
 [ 0. -1.  2. -1.  0.]
 [ 0.  0. -1.  2. -1.]
 [ 0.  0.  0. -1.  2.]]


In [3]:
from scipy.linalg import lu
P, L, U = lu(matriz_tribanda)
print(U)

[[ 2.         -1.          0.          0.          0.        ]
 [ 0.          1.5        -1.          0.          0.        ]
 [ 0.          0.          1.33333333 -1.          0.        ]
 [ 0.          0.          0.          1.25       -1.        ]
 [ 0.          0.          0.          0.          1.2       ]]


In [4]:
def ThomasM(DP, DS, DI, b):
    n = len(DP)
    x = np.zeros(n)

    # Eliminación para obtener un sistema triangular inferior (eliminación de DS)
    # Se recorre desde la penúltima fila hasta la primera
    for i in range(n - 2, -1, -1):
        factor = DS[i] / DP[i + 1]
        DP[i] = DP[i] - factor * DI[i]
        b[i] = b[i] - factor * b[i + 1]

    # Sustitución hacia adelante para resolver el sistema triangular inferior
    x[0] = b[0] / DP[0]
    for i in range(1, n):
        x[i] = (b[i] - DI[i - 1] * x[i - 1]) / DP[i]
    return x


In [5]:
solucion = ThomasM(DP.copy(), DS.copy(), DI.copy(), b.copy())
print("Solución con sustitución hacia adelante:", solucion)
print("Solución con LA.solve:", LA.solve(matriz_tribanda, b))

Solución con sustitución hacia adelante: [2.5 4.  4.5 4.  2.5]
Solución con LA.solve: [2.5 4.  4.5 4.  2.5]
