# Tarea 1 **Análisis Númerico**

#### INTEGRANTES:
Andrés González Ortega, Angel Vences Adame, Jair Eduardo Molina Lopez

## Ejercicio 1

###  Programe la multiplicación de matrices por bloques y compare tiempos de ejecuion contra el programa realizado en clase. Ojo, el nuevo programa debe ser más rápido, escoja tamaños de 10 hasta 100.

In [ ]:
import numpy as np
import timeit

def matmult_bloques(M,N):
  if M.shape[1] != N.shape[0]:
    print("No se puede multiplicar estas matrices")
  else:
    #obtenemos los puntos medios

    a1 = M.shape[0] // 2
    a2 = M.shape[1] // 2
    b1 = N.shape[0] // 2
    b2 = N.shape[1] // 2

    # Dividimos las matrices en bloques
    M11 = M[:a1, :a2] # superior izquierda
    M12 = M[:a1, a2:] # superior derecha
    M21 = M[a1:, :a2] # inferior izquierda
    M22 = M[a1:, a2:] # inferior derecha

    N11 = N[:b1, :b2] # superior izquierda
    N12 = N[:b1, b2:] # superior derecha
    N21 = N[b1:, :b2] # inferior izquierda
    N22 = N[b1:, b2:] # inferior derecha

  # Calculamos los bloques de la matriz C
    C11 = np.dot(N11, M11) + np.dot(N12, M21)
    C12 = np.dot(N11, M12) + np.dot(N12, M22)
    C21 = np.dot(N21, M11) + np.dot(N22, M21)
    C22 = np.dot(N21, M12) + np.dot(N22, M22)

    # Combinamos los bloques para formar la matriz C completa
    C = np.block([[C11, C12], [C21, C22]])
    return C

In [ ]:
#comprobamos resultado
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])

print(matmult_bloques(A,A))
A @ A

[[ 90 100 110 120]
 [202 228 254 280]
 [314 356 398 440]
 [426 484 542 600]]


array([[ 90, 100, 110, 120],
       [202, 228, 254, 280],
       [314, 356, 398, 440],
       [426, 484, 542, 600]])

In [ ]:
#Comparamos con nuestra función creada en clase
def MultMat(Mat1, Mat2):
    """
    Realiza la multiplicación de dos matrices.

    Parámetros:
    -----------
    Mat1 : numpy.ndarray
        Una matriz bidimensional de forma (n, m), donde 'n' es el número de filas
        y 'm' es el número de columnas.
    Mat2 : numpy.ndarray
        Una matriz bidimensional de forma (m, p), donde 'm' es el número de filas
        (debe coincidir con el número de columnas de Mat1) y 'p' es el número de
        columnas.

    Retorna:
    --------
    numpy.ndarray
        Una matriz bidimensional de forma (n, p) que representa el resultado de
        la multiplicación de Mat1 por Mat2.

    Ejemplo:
    --------
    >>> Mat1 = np.array([[1, 2, 3], [4, 5, 6]])
    >>> Mat2 = np.array([[7, 8], [9, 10], [11, 12]])
    >>> MultMat(Mat1, Mat2)
    array([[ 58.,  64.],
           [139., 154.]])
    """
    # Inicializa una matriz de ceros con las dimensiones adecuadas
    Mat3 = np.zeros((Mat1.shape[0], Mat2.shape[1]))

    # Itera sobre cada fila de la primera matriz
    for row in range(Mat1.shape[0]):
        # Itera sobre cada columna de la segunda matriz
        for col in range(Mat2.shape[1]):
            # Realiza la multiplicación y suma los productos
            for aux in range(Mat2.shape[0]):
                Mat3[row, col] += Mat1[row, aux] * Mat2[aux, col]

    # Devuelve la matriz resultante
    return Mat3

In [ ]:
A = np.random.rand(50,50)
B = np.random.rand(50,50)

# Medir el tiempo de ejecución
time = timeit.timeit(lambda: MultMat(A,B), number=1000)

print(f"Tiempo de ejecución: {time:.6f} segundos para 1000 ejecuciones")

#time = timeit.timeit(lambda: mat_mult_bloques(A,B), number=1000)

#print(f"Tiempo de ejecución: {time:.6f} segundos para 1000 ejecuciones")

time = timeit.timeit(lambda: matmult_bloques(A,B), number=1000)

print(f"Tiempo de ejecución: {time:.6f} segundos para 1000 ejecuciones")

Tiempo de ejecución: 93.817031 segundos para 1000 ejecuciones
Tiempo de ejecución: 0.114831 segundos para 1000 ejecuciones
