### Haga un programa que realice la potencia de una matriz de tamaño 50x50. De preferencia utilice la multiplicación de matriz por bloques.

In [1]:
import numpy as np
import timeit

def matmult_bloques(M,N):
  if M.shape[1] != N.shape[0]:
    print("No se puede multiplicar estas matrices")
  else:
    #obtenemos los puntos medios

    a1 = M.shape[0] // 2
    a2 = M.shape[1] // 2
    b1 = N.shape[0] // 2
    b2 = N.shape[1] // 2

    # Dividimos las matrices en bloques
    M11 = M[:a1, :a2] # superior izquierda
    M12 = M[:a1, a2:] # superior derecha
    M21 = M[a1:, :a2] # inferior izquierda
    M22 = M[a1:, a2:] # inferior derecha

    N11 = N[:b1, :b2] # superior izquierda
    N12 = N[:b1, b2:] # superior derecha
    N21 = N[b1:, :b2] # inferior izquierda
    N22 = N[b1:, b2:] # inferior derecha

  # Calculamos los bloques de la matriz C
    C11 = np.dot(N11, M11) + np.dot(N12, M21)
    C12 = np.dot(N11, M12) + np.dot(N12, M22)
    C21 = np.dot(N21, M11) + np.dot(N22, M21)
    C22 = np.dot(N21, M12) + np.dot(N22, M22)

    # Combinamos los bloques para formar la matriz C completa
    C = np.block([[C11, C12], [C21, C22]])
    return C

In [2]:
# Potencia de una matriz
def potencia50(M):
  if M.shape[0] != M.shape[1]:
    print("No se puede realizar la operación")
  else:
    Mn = M
    #realizamos la operacion 49 veces porque en la primera ya elevamos a la segunda potencia.
    for i in range(49):
      Mn = matmult_bloques(Mn,M) # Usamo la función de la tarea
    return Mn

In [3]:
A = np.ones((3, 3))
matriz_potencia_50 = np.linalg.matrix_power(A, 50)
print(matriz_potencia_50)
potencia50(A)

[[2.39299329e+23 2.39299329e+23 2.39299329e+23]
 [2.39299329e+23 2.39299329e+23 2.39299329e+23]
 [2.39299329e+23 2.39299329e+23 2.39299329e+23]]


array([[2.39299329e+23, 2.39299329e+23, 2.39299329e+23],
       [2.39299329e+23, 2.39299329e+23, 2.39299329e+23],
       [2.39299329e+23, 2.39299329e+23, 2.39299329e+23]])