### Crear un programa que aplique una rotación de un vector tridimensional mediante una matriz de rotación.

In [4]:
#Rotacion Vector Tridimensional
#Analogamente al ejercicio anterior, solo que dividimos en 3 casos dependiendo del eje de rotacion
def RVT(A,grad,axis):
    rad=np.radians(grad)
    if axis == 'x':
        MR = [[1,0,0],[0,np.cos(rad),-np.sin(rad)],[0, np.sin(rad),np.cos(rad)]]
    elif axis == 'y':
        MR = [[np.cos(rad),0,np,sin(rad)],[0,1,0],[-np.sin(rad),0,np.cos(rad)]]
    else:
        MR=[[np.cos(rad),-np.sin(rad),0],[np.sin(rad),np.cos(rad),0],[0,0,1]]

    return(np.round(np.dot(MR,A),10))

A = [[1,0,0],[0,3,0],[0,0,8]]
print(RVT(A,90,'x'))

[[ 1.  0.  0.]
 [ 0.  0. -8.]
 [ 0.  3.  0.]]
