<a href="https://colab.research.google.com/github/GonorAndres/Analisis_Numerico_2025-2/blob/main/Practica2/Ejercicio26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Ejercicio 26 - Factorización de Cholesky

Encontrar la factorización de Cholesky de $A$ para las siguientes matrices:

$$
A = \begin{bmatrix}
2 & -1 & 0 \\
-1 & 2 & -1 \\
0 & -1 & 2
\end{bmatrix}$$


Utilizando:

- (a) $A = LL^T$  
- (b) $A = \hat{L} \hat{D} \hat{L}^T$

In [36]:
import numpy as np
# Factorización de Cholesky clásica: A = L @ L.T
# Aquí no verificamos que la matriz sea definida positiva pero si se usa este algoritmo se da por hecho que el usuaria sabe que es una matriz definida positiva
def cholesky(A):
    n = A.shape[0]
    L = np.zeros_like(A)

    for i in range(n):
        for j in range(i+1): # empezamos en el renglón depues del pivote i así que el numero de elementos del renglon debajo de la diagonal es (i+1) y garantizamos que siempre j=<i, una matriz triangular inferior
            cumsum = 0.0
            for k in range(j):
              cumsum += L[i][k]*L[j][k]
            if i == j: # en las diagonales el proceso es diferente
                L[i][j] = np.sqrt(A[i][i] - cumsum)
            else: # en los renglones aplicamos el algoritmo de eliminación cholesky
                L[i][j] = (A[i][j] - cumsum) / L[j][j]
    if not np.allclose(L @ L.T, A):
        L = print("La matriz no es definida positiva ERROR")

    return L

In [37]:
def cholesky_LDLT(A):
    n = A.shape[0]
    L = np.eye(n)   # L con 1s en la diagonal
    D = np.zeros(n) # para el vector lleno de las entradas de la diagonal

    for i in range(n):
        for j in range(i):
            suma = 0.0
            for k in range(j):
                suma += L[i][k] * D[k] * L[j][k] #sumamos la combinación lineales

            L[i][j] = (A[i][j] - suma) / D[j] #hacemos la eliminación y la división no será cero porque el ciclo solo se ejecuta recién en la segunda vuelta

        suma_diag = 0.0
        for k in range(i):
            suma_diag += (L[i][k] ** 2) * D[k] #sacamos la escala para D

        D[i] = A[i][i] - suma_diag

    D = np.diag(D) # convertimos el vector de la diagonal en una matriz diagonal

    if not np.allclose(L @ D @ L.T, A):
      R = print("La matriz no es definida positiva ERROR")
    else:
      R = L, D

    return R

In [39]:
# Matriz A
A = np.array([
    [2, -1, 0],
    [-1, 2, -1],
    [0, -1, 2]
], dtype=float)

M = A

print(f"Matriz L de LDL^T:\n{cholesky(M)}\n")
print(f"Matriz L de LDLT\n{cholesky_LDLT(M)[0]} y \nmatrid D\n{cholesky_LDLT(M)[1]}")

Matriz L de LDL^T:
[[ 1.41421356  0.          0.        ]
 [-0.70710678  1.22474487  0.        ]
 [ 0.         -0.81649658  1.15470054]]

Matriz L de LDLT
[[ 1.          0.          0.        ]
 [-0.5         1.          0.        ]
 [ 0.         -0.66666667  1.        ]] y 
matrid D
[[2.         0.         0.        ]
 [0.         1.5        0.        ]
 [0.         0.         1.33333333]]


$$B = \begin{bmatrix}
4 & 1 & 1 & 1 \\
1 & 3 & -1 & 1 \\
1 & -1 & 2 & 0 \\
1 & 1 & 0 & 2
\end{bmatrix}
$$


Utilizando:

- (a) $A = LL^T$  
- (b) $A = \hat{L} \hat{D} \hat{L}^T$

In [40]:
# Matriz B
B = np.array([
    [4, 1, 1, 1],
    [1, 3, -1, 1],
    [1, -1, 2, 0],
    [1, 1, 0, 2]
], dtype=float)

M = B

print(f"Matriz L de LDL^T:\n{cholesky(M)}\n")
print(f"Matriz L de LDLT\n{cholesky_LDLT(M)[0]} y \nmatrid D\n{cholesky_LDLT(M)[1]}")

Matriz L de LDL^T:
[[ 2.          0.          0.          0.        ]
 [ 0.5         1.6583124   0.          0.        ]
 [ 0.5        -0.75377836  1.08711461  0.        ]
 [ 0.5         0.45226702  0.0836242   1.24034735]]

Matriz L de LDLT
[[ 1.          0.          0.          0.        ]
 [ 0.25        1.          0.          0.        ]
 [ 0.25       -0.45454545  1.          0.        ]
 [ 0.25        0.27272727  0.07692308  1.        ]] y 
matrid D
[[4.         0.         0.         0.        ]
 [0.         2.75       0.         0.        ]
 [0.         0.         1.18181818 0.        ]
 [0.         0.         0.         1.53846154]]



$$
C = \begin{bmatrix}
4 & 1 & -1 & 0 \\
1 & 3 & -1 & 0 \\
-1 & -1 & 5 & 2 \\
0 & 0 & 2 & 4
\end{bmatrix}$$

Utilizando:

- (a) $A = LL^T$  
- (b) $A = \hat{L} \hat{D} \hat{L}^T$

In [41]:

# Matriz C
C = np.array([
    [4, 1, -1, 0],
    [1, 3, -1, 0],
    [-1, -1, 5, 2],
    [0, 0, 2, 4]
], dtype=float)

M = C

print(f"Matriz L de LDL^T:\n{cholesky(M)}\n")
print(f"Matriz L de LDLT\n{cholesky_LDLT(M)[0]} y \nmatrid D\n{cholesky_LDLT(M)[1]}")


Matriz L de LDL^T:
[[ 2.          0.          0.          0.        ]
 [ 0.5         1.6583124   0.          0.        ]
 [-0.5        -0.45226702  2.13200716  0.        ]
 [ 0.          0.          0.93808315  1.76635217]]

Matriz L de LDLT
[[ 1.          0.          0.          0.        ]
 [ 0.25        1.          0.          0.        ]
 [-0.25       -0.27272727  1.          0.        ]
 [ 0.          0.          0.44        1.        ]] y 
matrid D
[[4.         0.         0.         0.        ]
 [0.         2.75       0.         0.        ]
 [0.         0.         4.54545455 0.        ]
 [0.         0.         0.         3.12      ]]


$$
D = \begin{bmatrix}
6 & 2 & 1 & -1 \\
2 & 4 & 1 & 0 \\
1 & 1 & 4 & -1 \\
-1 & 0 & -1 & 3
\end{bmatrix}
$$

Utilizando:

- (a) $A = LL^T$  
- (b) $A = \hat{L} \hat{D} \hat{L}^T$

In [42]:

# Matriz D
D = np.array([
    [6, 2, 1, -1],
    [2, 4, 1, 0],
    [1, 1, 4, -1],
    [-1, 0, -1, 3]
], dtype=float)

M = D

print(f"Matriz L de LDL^T:\n{cholesky(M)}\n")
print(f"Matriz L de LDLT\n{cholesky_LDLT(M)[0]} y \nmatrid D\n{cholesky_LDLT(M)[1]}")

Matriz L de LDL^T:
[[ 2.44948974  0.          0.          0.        ]
 [ 0.81649658  1.82574186  0.          0.        ]
 [ 0.40824829  0.36514837  1.92353841  0.        ]
 [-0.40824829  0.18257419 -0.46788772  1.60657433]]

Matriz L de LDLT
[[ 1.          0.          0.          0.        ]
 [ 0.33333333  1.          0.          0.        ]
 [ 0.16666667  0.2         1.          0.        ]
 [-0.16666667  0.1        -0.24324324  1.        ]] y 
matrid D
[[6.         0.         0.         0.        ]
 [0.         3.33333333 0.         0.        ]
 [0.         0.         3.7        0.        ]
 [0.         0.         0.         2.58108108]]
