<a href="https://colab.research.google.com/github/GonorAndres/Analisis_Numerico_2025-2/blob/main/Practica2/Ejercicio20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Ejercicio 20

Dado el sistema \( Ax = b \):

#### (a) Resolver con **eliminación Gaussiana** para:


$$ A = \begin{bmatrix}
2 & 4 & -2 \\
4 & 9 & -3 \\
-2 & -1 & 7
\end{bmatrix} ;
b =
\begin{bmatrix}
2 \\
8 \\
10
\end{bmatrix} $$


#### (b) Usar **factorización LU** de \( A \) para resolver el sistema $ Ay = c $, donde:

$$
c =
\begin{bmatrix}
4 \\
8 \\
-6
\end{bmatrix}
$$


In [ ]:
#Funciones de la clase

import numpy as np
from numpy import linalg as LA


def SustitucionDelante(Mat, b):
    """
    Realiza la sustitución hacia adelante para resolver un sistema de ecuaciones lineales
    representado por una matriz triangular inferior.

    Parámetros:
    -----------
    Mat : numpy.ndarray
        Una matriz triangular inferior de tamaño n x n.
    b : numpy.ndarray
        Un vector de términos independientes de tamaño n.

    Retorna:
    --------
    x : numpy.ndarray
        Un vector solución de tamaño n que satisface la ecuación Mat @ x = b.

    Descripción:
    ------------
    Esta función resuelve un sistema de ecuaciones lineales de la forma Mat @ x = b,
    donde Mat es una matriz triangular inferior. Utiliza el método de sustitución hacia adelante,
    comenzando desde la primera fila de la matriz y avanzando hacia la última.

    Ejemplo:
    --------
    >>> Mat = np.array([[1, 0, 0],
    ...                 [2, 3, 0],
    ...                 [4, 5, 6]])
    >>> b = np.array([1, 8, 32])
    >>> SustitucionDelante(Mat, b)
    array([1., 2., 3.])
    """
    n = Mat.shape[0]
    x = np.zeros(n)

    for i in range(n):
        SumCum = 0.0
        for j in range(i):
            SumCum += Mat[i, j] * x[j]
        x[i] = (b[i] - SumCum) / Mat[i, i]

    return x

def SustitucionAtras(Mat, b):
    """
    Realiza la sustitución hacia atrás para resolver un sistema de ecuaciones lineales
    representado por una matriz triangular superior.

    Parámetros:
    -----------
    Mat : numpy.ndarray
        Una matriz triangular superior de tamaño n x n.
    b : numpy.ndarray
        Un vector de términos independientes de tamaño n.

    Retorna:
    --------
    x : numpy.ndarray
        Un vector solución de tamaño n que satisface la ecuación Mat @ x = b.

    Descripción:
    ------------
    Esta función resuelve un sistema de ecuaciones lineales de la forma Mat @ x = b,
    donde Mat es una matriz triangular superior. Utiliza el método de sustitución hacia atrás,
    comenzando desde la última fila de la matriz y avanzando hacia la primera.

    Ejemplo:
    --------
    >>> Mat = np.array([[3, 2, 1],
    ...                 [0, 2, 1],
    ...                 [0, 0, 1]])
    >>> b = np.array([6, 4, 1])
    >>> SustitucionAtras(Mat, b)
    array([1., 1., 1.])
    """
    n = Mat.shape[0]
    x = np.zeros(n)

    for i in range(n-1, -1, -1):
        SumCum = 0.0
        for j in range(i+1, n):
            SumCum += Mat[i, j] * x[j]
        x[i] = (b[i] - SumCum) / Mat[i, i]

    return x

def LU(A):
  U=np.copy(A)
  L=np.eye(A.shape[0])

  for i in range(A.shape[0]):
    Li=np.eye(A.shape[0])
    for j in range(i+1,A.shape[0]):
      Li[j,i]=-U[j,i]/U[i,i]
      L[j,i]=U[j,i]/U[i,i]
    U=Li@U
  return L,U

def SolverLU(A,b):
  L,U=LU(A)
  # El sistema que se resuelve es Ly=b
  y=SustitucionDelante(L, b)
  # El sistema que se resuelve es Ux=y
  x=SustitucionAtras(U, y)

  return x

In [ ]:
#Algoritmo sustituación Gaussiana
def elim_gauss(A, b):
    n = len(b)

    for k in range(n - 1): # el rango es uno menos que el numero de filas porque para la ultima fila solo habrá un elemento y ya no es posible usar el pivote para eliminar más variables pues solo existe una y
        if (A[k, k] == 0):
            print("Pivote nulo, error al realizar el algoritmo")
            return

        for i in range(k + 1, n): # empezamos en la fila debajo del pivote es decir la fila k + 1, seguimos recorriendo cada fila hasta que todas las entradas de la columna debajo de la elemento k,k sean cero
            m = A[i, k] / A[k, k]
            A[i, k:] = A[i, k:] - (m * A[k, k:]) # restamos la fila del pivote a la fila de cada renglon después del pivote k, empezamos desde la diagonal porque por definición los elementos antes de esta ya son cero
            b[i] = b[i]- (m * b[k]) # también aplicamos la operación a las igualdades del sistema

    # usamos el algoritmo para resolver una ecuación triangular vista en clase

    x = SustitucionAtras(A, b)

    return x


#### (a) Resolver con **eliminación Gaussiana** para:


$$ A = \begin{bmatrix}
2 & 4 & -2 \\
4 & 9 & -3 \\
-2 & -1 & 7
\end{bmatrix} ;
b =
\begin{bmatrix}
2 \\
8 \\
10
\end{bmatrix} $$

In [ ]:
#Ejericio a
A = np.array([[ 2.0,  4, -2],
              [ 4,  9, -3],
              [-2, -1,  7]])
b = np.array([2.0, 8, 10])

x = elim_gauss(A, b)
print(x)        # [-7,  4,  0] hecho en calculadora

[-7.  4.  0.]


#### (b) Usar **factorización LU** de \( A \) para resolver el sistema $ Ay = c $, donde:

$$
c =
\begin{bmatrix}
4 \\
8 \\
-6
\end{bmatrix}
$$

In [ ]:
#Ejericio b
A = np.array([[ 2.0,  4, -2],
              [ 4,  9, -3],
              [-2, -1,  7]])
c = np.array([4.0, 8, -6])

x = SolverLU(A,c)

print(x)

[-1.  1. -1.]
