<a href="https://colab.research.google.com/github/GonorAndres/Analisis_Numerico_2025-2/blob/main/Practica2/Ejercicio22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Ejercicio 22

Dada la matriz:

$$
A = \begin{pmatrix}
1 & 0 & 0 & 0 & 1 \\
-1 & 1 & 0 & 0 & 1 \\
-1 & -1 & 1 & 0 & 1 \\
-1 & -1 & -1 & 1 & 1 \\
-1 & -1 & -1 & -1 & 1
\end{pmatrix}
$$

### (a) ¿Qué sucede con la Eliminación Gaussiana con pivoteo parcial?

Observamos que:

- La matriz es triangular inferior con unos en la diagonal.
- Todos los pivotes son 1, y los elementos debajo del pivote son -1 o 0. Por lo tanto, el **pivoteo parcial no realiza ningún intercambio de filas**, ya que no hay un valor absoluto más grande que uno y todas las diagonales son 1, y la eliminación avanza normalmente.
- La estructura especial puede dar lugar a **matrices mal condicionadas** si se extiende a tamaños grandes porque cada vez los reglones son más pareceidos en dirección, es decir el angulo entre ello va siendo más pequeño, lo que genere que cada vez que crece la dimensión, existan un par de vectores que parecen ser linealmente dependientes.

Sea $u_1=a_{(n-1)\bullet} $ el penultimo renglón de la matriz.


Sea $u_2=a_{(n)\bullet} $ el último renglón de la matriz.
$$cos(\theta)=\frac{u_1\bullet u_2}{\|u_1\|\|u_2\|}=
\frac{(n-1)-1}{ \sqrt{n} \sqrt{n}}=
\frac{n-2}{n}
$$

por tanto cada vez que n sea más grande los dos últimos vectores serán "más cercanos" de ser linealmente dependientes, aumentando la mala condicionalidad.


---


In [9]:
#Funciones de la clase


import numpy as np

def SubMat(Mat, ren, col):
    """
    Crea una submatriz eliminando un renglón y una columna específicos de la matriz original.

    Parámetros:
    -----------
    Mat : numpy.ndarray
        Matriz original de la cual se obtendrá la submatriz.
    ren : int
        Índice del renglón que se eliminará de la matriz.
    col : int
        Índice de la columna que se eliminará de la matriz.

    Retorna:
    --------
    numpy.ndarray
        Submatriz resultante después de eliminar el renglón y la columna especificados.

    Ejemplo:
    --------
    >>> Mat = np.array([[1, 2, 3],
    ...                [4, 5, 6],
    ...                [7, 8, 9]])
    >>> SubMat(Mat, 1, 1)
    array([[1, 3],
           [7, 9]])
    """
    # Crear una copia de la matriz original para no modificarla
    M1 = np.copy(Mat)

    # Eliminar el renglón especificado
    M1 = np.delete(M1, ren, axis=0)

    # Eliminar la columna especificada
    M1 = np.delete(M1, col, axis=1)

    return M1


import numpy as np

def Det(Mat):
    """
    Calcula el determinante de una matriz cuadrada de manera recursiva.

    Parámetros:
    -----------
    Mat : numpy.ndarray
        Matriz cuadrada de la cual se calculará el determinante.
        Debe ser de tamaño n x n, donde n >= 2.

    Retorna:
    --------
    float
        El determinante de la matriz.

    Ejemplo:
    --------
    >>> Mat = np.array([[1, 2],
    ...                [3, 4]])
    >>> Det(Mat)
    -2.0

    >>> Mat = np.array([[6, 1, 1],
    ...                [4, -2, 5],
    ...                [2, 8, 7]])
    >>> Det(Mat)
    -306.0
    """
    # Caso base: matriz 2x2
    if Mat.shape[0] == 2 and Mat.shape[1] == 2:
        return Mat[0][0] * Mat[1][1] - (Mat[0][1] * Mat[1][0])

    # Caso recursivo: matrices más grandes
    deter = 0.0
    for col in range(Mat.shape[0]):
        # Calcula el cofactor y suma al determinante
        deter += ((-1) ** col) * Mat[0][col] * Det(SubMat(Mat, 0, col))
    return deter


import numpy as np

def Transpuesta(Mat):
    """
    Calcula la transpuesta de una matriz cuadrada modificando la matriz original.

    Parámetros:
    -----------
    Mat : numpy.ndarray
        Matriz cuadrada de tamaño n x n que se transpondrá.
        La matriz se modificará in situ.

    Retorna:
    --------
    numpy.ndarray
        La matriz transpuesta. La matriz original también se modifica.

    Ejemplo:
    --------
    >>> Mat = np.array([[1, 2, 3],
    ...                [4, 5, 6],
    ...                [7, 8, 9]])
    >>> Transpuesta(Mat)
    array([[1, 4, 7],
           [2, 5, 8],
           [3, 6, 9]])
    """
    for ren in range(Mat.shape[0]):
        for col in range(Mat.shape[1]):
            if ren < col:
                # Intercambia los elementos para obtener la transpuesta
                Mat[ren, col], Mat[col, ren] = Mat[col, ren], Mat[ren, col]
    return Mat



import numpy as np

def Cofactores(Mat):
    """
    Calcula la matriz de cofactores de una matriz cuadrada.

    Parámetros:
    -----------
    Mat : numpy.ndarray
        Matriz cuadrada de tamaño n x n para la cual se calcularán los cofactores.

    Retorna:
    --------
    numpy.ndarray
        Matriz de cofactores, donde cada elemento es el cofactor correspondiente
        de la matriz original.

    Ejemplo:
    --------
    >>> Mat = np.array([[1, 2],
    ...                [3, 4]])
    >>> Cofactores(Mat)
    array([[ 4., -3.],
           [-2.,  1.]])
    """
    # Crear una matriz de ceros del mismo tamaño que Mat para almacenar los cofactores
    Cofa = np.zeros_like(Mat, dtype=float)

    # Calcular el cofactor para cada elemento de la matriz
    for ren in range(Mat.shape[0]):
        for col in range(Mat.shape[1]):
            # Calcular el determinante de la submatriz (menor) y aplicar el signo
            Cofa[ren, col] = ((-1) ** (ren + col)) * Det(SubMat(Mat, ren, col))
    return Cofa



import numpy as np

def Inv(Mat):
    """
    Calcula la inversa de una matriz cuadrada utilizando la matriz de cofactores.

    Parámetros:
    -----------
    Mat : numpy.ndarray
        Matriz cuadrada de tamaño n x n que se invertirá.
        Debe ser una matriz no singular (su determinante debe ser distinto de cero).

    Retorna:
    --------
    numpy.ndarray
        La matriz inversa de la matriz original.

    Ejemplo:
    --------
    >>> Mat = np.array([[4, 7],
    ...                [2, 6]])
    >>> Inv(Mat)
    array([[ 0.6, -0.7],
           [-0.2,  0.4]])
    """
    # Calcular el determinante de la matriz
    deter = Det(Mat)

    # Verificar si la matriz es singular (determinante = 0)
    if deter == 0:
        raise ValueError("La matriz es singular y no tiene inversa.")

    # Calcular la matriz de cofactores
    Cofac = Cofactores(Mat)

    # Transponer la matriz de cofactores para obtener la matriz adjunta
    Cofac = Transpuesta(Cofac)

    # Calcular la inversa multiplicando la adjunta por 1/determinante
    Inversa = (1 / deter) * Cofac

    return Inversa



A=np.array([[2,3,-4],[0,-4,2],[1,-1,5]])
b=np.array([1.0,1.0,1.0])

import numpy as np

def SolveInv(Mat, vec):
    """
    Resuelve un sistema de ecuaciones lineales utilizando la matriz inversa.

    Parámetros:
    -----------
    Mat : numpy.ndarray
        Matriz cuadrada de coeficientes del sistema de ecuaciones.
        Debe ser una matriz no singular (su determinante debe ser distinto de cero).

    vec : numpy.ndarray
        Vector de términos independientes.
        Su tamaño debe coincidir con el número de filas de la matriz `Mat`.

    Retorna:
    --------
    numpy.ndarray
        Vector solución del sistema de ecuaciones `Mat @ x = vec`.

    Excepciones:
    ------------
    ValueError
        Se lanza un error si la matriz `Mat` no es invertible.

    Ejemplo:
    --------
    >>> Mat = np.array([[2, 1],
    ...                 [5, 3]])
    >>> vec = np.array([4, 10])
    >>> SolveInv(Mat, vec)
    array([2., 0.])

    """
    # Calcular la inversa de la matriz
    InvMat = Inv(Mat)

    # Multiplicar la inversa por el vector de términos independientes
    Solucion = InvMat @ vec

    return Solucion


import numpy as np
from numpy import linalg as LA


def SustitucionDelante(Mat, b):
    """
    Realiza la sustitución hacia adelante para resolver un sistema de ecuaciones lineales
    representado por una matriz triangular inferior.

    Parámetros:
    -----------
    Mat : numpy.ndarray
        Una matriz triangular inferior de tamaño n x n.
    b : numpy.ndarray
        Un vector de términos independientes de tamaño n.

    Retorna:
    --------
    x : numpy.ndarray
        Un vector solución de tamaño n que satisface la ecuación Mat @ x = b.

    Descripción:
    ------------
    Esta función resuelve un sistema de ecuaciones lineales de la forma Mat @ x = b,
    donde Mat es una matriz triangular inferior. Utiliza el método de sustitución hacia adelante,
    comenzando desde la primera fila de la matriz y avanzando hacia la última.

    Ejemplo:
    --------
    >>> Mat = np.array([[1, 0, 0],
    ...                 [2, 3, 0],
    ...                 [4, 5, 6]])
    >>> b = np.array([1, 8, 32])
    >>> SustitucionDelante(Mat, b)
    array([1., 2., 3.])
    """
    n = Mat.shape[0]
    x = np.zeros(n)

    for i in range(n):
        SumCum = 0.0
        for j in range(i):
            SumCum += Mat[i, j] * x[j]
        x[i] = (b[i] - SumCum) / Mat[i, i]

    return x

def SustitucionAtras(Mat, b):
    """
    Realiza la sustitución hacia atrás para resolver un sistema de ecuaciones lineales
    representado por una matriz triangular superior.

    Parámetros:
    -----------
    Mat : numpy.ndarray
        Una matriz triangular superior de tamaño n x n.
    b : numpy.ndarray
        Un vector de términos independientes de tamaño n.

    Retorna:
    --------
    x : numpy.ndarray
        Un vector solución de tamaño n que satisface la ecuación Mat @ x = b.

    Descripción:
    ------------
    Esta función resuelve un sistema de ecuaciones lineales de la forma Mat @ x = b,
    donde Mat es una matriz triangular superior. Utiliza el método de sustitución hacia atrás,
    comenzando desde la última fila de la matriz y avanzando hacia la primera.

    Ejemplo:
    --------
    >>> Mat = np.array([[3, 2, 1],
    ...                 [0, 2, 1],
    ...                 [0, 0, 1]])
    >>> b = np.array([6, 4, 1])
    >>> SustitucionAtras(Mat, b)
    array([1., 1., 1.])
    """
    n = Mat.shape[0]
    x = np.zeros(n)

    for i in range(n-1, -1, -1):
        SumCum = 0.0
        for j in range(i+1, n):
            SumCum += Mat[i, j] * x[j]
        x[i] = (b[i] - SumCum) / Mat[i, i]

    return x

def LU(A):
  U=np.copy(A)
  L=np.eye(A.shape[0])

  for i in range(A.shape[0]):
    Li=np.eye(A.shape[0])
    for j in range(i+1,A.shape[0]):
      Li[j,i]=-U[j,i]/U[i,i]
      L[j,i]=U[j,i]/U[i,i]
    U=Li@U
  return L,U

def Solver_LU(A,b):
  L,U=LU(A)
  # El sistema que se resuelve es Ly=b
  y=SustitucionDelante(L, b)
  # El sistema que se resuelve es Ux=y
  x=SustitucionAtras(U, y)

  return x

In [14]:
## Funciones de ejercicios anteriores de la tarea
def LU_parcial(A):
    n = A.shape[0]
    U = np.copy(A)
    L = np.eye(n)
    P = np.eye(n)

    for i in range(n):
        # Encontrar fila con valor absoluto máximo en la columna i
        max_val = abs(U[i, i])
        max_row = i
        for k in range(i+1, n):
            if abs(U[k, i]) > max_val:
                max_val = abs(U[k, i])
                max_row = k

        # Intercambiar filas si es necesario
        if max_row != i:
            U[[i, max_row], :] = U[[max_row, i], :] # el corchete dentro de la posición de las filas sirve como multiasignación así no creamos variables de apoyo
            P[[i, max_row], :] = P[[max_row, i], :]
            if i > 0: # tenemos que solo se intercambia después de la primera interación por justamente en la primer vuelta no hemos calculado nada y sigue siendo la identidad solo intercambiariamos ceros identicos
                L[[i, max_row], :i] = L[[max_row, i], :i] # sin embargo para la segunda vuelta ya habremos calculado por lo menos un elemento que no esta en la diagonal de la columna 1, entonces ya es necesario intercambiar
                                                          # y solo intercambiamos hasta antes de la columna i, pues solo nos interesan la parte triangular inferior, la diagonal son unos por definición
        # Eliminación gaussiana
        for j in range(i+1, n):
            L[j, i] = U[j, i] / U[i, i]
            U[j, :] = U[j, :] - (L[j, i] * U[i, :])

    return P, L, U

def Solver_LUParcial(A, b):
    # Resuelve el sistema Ax = b usando la factorización LU con pivoteo parcial.
    # como Ax =b y PA = LU entonces LUx = PAx = Pb así resolvemos
    # LUx = Pb
    P, L, U = LU_parcial(A)
    Pb = P @ b
    z = SustitucionDelante(L, Pb)
    x = SustitucionAtras(U, z)
    return x

def LU_total(A):
    n = A.shape[0]
    U = np.copy(A)
    L = np.eye(n)
    P = np.eye(n)
    Q = np.eye(n)

    for i in range(n):
        # Buscar el índice del valor absoluto máximo en submatriz U[i:, i:]
        max_val = abs(U[i, i])
        max_row, max_col = i, i
        for r in range(i, n):
            for s in range(i, n):
                if abs(U[r, s]) > max_val:
                    max_val = abs(U[r, s])
                    max_row, max_col = r, s

        # Intercambiar filas si es necesario
        if max_row != i:
            U[[i, max_row], :] = U[[max_row, i], :] # el corchete dentro de la posición de las filas sirve como multiasignación así no creamos variables de apoyo
            P[[i, max_row], :] = P[[max_row, i], :]
            if i > 0: # tenemos que solo se intercambia después de la primera interación por justamente en la primer vuelta no hemos calculado nada y sigue siendo la identidad solo intercambiariamos ceros identicos
                L[[i, max_row], :i] = L[[max_row, i], :i] # sin embargo para la segunda vuelta ya habremos calculado por lo menos un elemento que no esta en la diagonal de la columna 1, entonces ya es necesario intercambiar
                                                          # y solo intercambiamos hasta antes de la columna i, pues solo nos interesan la parte triangular inferior, la diagonal son unos por definición


        # Intercambio de columnas si es necesario
        if max_col != i:
            U[:, [i, max_col]] = U[:, [max_col, i]]
            Q[:, [i, max_col]] = Q[:, [max_col, i]]
            # Ahora vemos que no intercambiamos las columnas de L en ninguna ocasión porque L guarda en la parte triangular inferior todos los pivotes correspondientes a cada fila para la eliminación de los terminos debajo de la diagonal
            # sin embargo ahora los renglones no se movieron y el pivote de eliminación sigue correspondiendo a esa misma fila, tampoco debemos tener cuidado en el cambio de orden de las variables
            # pues el pivote afecta a toda la fila por igual no importa en que orden se encuentre y el cambio en U no afecta en nada

        # Eliminación gaussiana
        for j in range(i+1, n):
            L[j, i] = U[j, i] / U[i, i]
            U[j, :] = U[j, :] - (L[j, i] * U[i, :])

    return P, L, U, Q

def Solver_LUtotal(A, b):
    # Resuelve el sistema Ax = b usando la factorización LU con pivoteo total.
    # como Ax = b y PAQ = LU entonces PA = LUQ^-1, LUQ^-1x = PAx = Pb entonces sea y = Q^-1x tenemos que LUy = Pb
    #  Resolvemos LUy = Pb
    P, L, U, Q = LU_total(A)
    Pb = P @ b
    z = SustitucionDelante(L, Pb)
    y = SustitucionAtras(U, z)
    # Resolvemos y = Q^-1x donde x = Qy
    x = Q @ y

    return x

### (b) Comportamiento de la condición de la matriz al resolver sistemas con eliminación gaussiana con pivoteo parcial






In [12]:
# Creamos una función para crear las matrices como la del ejemplo de tamaño n
def matriz_22(n):
    A = np.zeros((n, n),dtype=float)
    for i in range(n):
        for j in range(n):
            if i == j:
                A[i, j] = 1
            elif i > j:
                A[i, j] = -1
        A[i, -1] = 1  # última columna = 1
    return A

def v_b(r):
    return np.random.randint(1, r+1, size=r).astype(float)

In [22]:
# Resolvamos para b

M1 = matriz_22(6)
M2 = matriz_22(9)
M3 = matriz_22(15)
M4 = matriz_22(30)
M5 = matriz_22(52)

R1 = Solver_LUParcial(M1, v_b(6))
R2 = Solver_LUParcial(M2, v_b(9))
R3 = Solver_LUParcial(M3, v_b(15))
R4 = Solver_LUParcial(M4, v_b(30))
R5 = Solver_LUParcial(M5, v_b(52))

c1 = np.linalg.cond(M1)
c2 = np.linalg.cond(M2)
c3 = np.linalg.cond(M3)
c4 = np.linalg.cond(M4)
c5 = np.linalg.cond(M5)

print(f"La condición de la matriz M1 es: {c1} y la solución Ax=b es: x= {R1}")
print(f"La condición de la matriz M2 es: {c2} y la solución Ax=b es: x= {R2}")
print(f"La condición de la matriz M3 es: {c3} y la solución Ax=b es: x= {R3}")
print(f"La condición de la matriz M4 es: {c4} y la solución Ax=b es: x= {R4}")
print(f"La condición de la matriz M5 es: {c5} y la solución Ax=b es: x= {R5}")

La condición de la matriz M1 es: 2.646401257792048 y la solución Ax=b es: x= [-0.75  0.5   0.    0.   -2.    2.75]
La condición de la matriz M2 es: 3.9457772176826267 y la solución Ax=b es: x= [ 2.26953125  1.5390625   0.078125   -0.84375     0.3125     -2.375
  0.25        1.5         6.73046875]
La condición de la matriz M2 es: 6.601454215265285 y la solución Ax=b es: x= [-2.56726074  3.86547852  1.73095703 -3.53808594 -3.07617188 -0.15234375
  1.6953125   2.390625   -2.21875    -1.4375      2.125       2.25
  6.5         0.          8.56726074]
La condición de la matriz M2 es: 13.317560182076937 y la solución Ax=b es: x= [  4.02684227   1.05368455  -4.8926309    1.21473819  -1.57052362
   1.85895276  -5.28209448   9.43581104  -4.12837791  -8.25675583
   0.48648834   8.97297668  -6.05404663   3.89190674  -8.21618652
   7.56762695   1.13525391  -2.72949219  -6.45898438   1.08203125
   9.1640625    5.328125    -4.34375     -0.6875      -5.375
   7.25        -7.5        -10.          -4

### (c) Rutina para factorizar la matriz con pivoteo total

In [ ]:
# Ya la habíamos hecho en el ejercicio 21, copiamos y pegamos aquí
def LU_total(A):
    n = A.shape[0]
    U = np.copy(A)
    L = np.eye(n)
    P = np.eye(n)
    Q = np.eye(n)

    for i in range(n):
        # Buscar el índice del valor absoluto máximo en submatriz U[i:, i:]
        max_val = abs(U[i, i])
        max_row, max_col = i, i
        for r in range(i, n):
            for s in range(i, n):
                if abs(U[r, s]) > max_val:
                    max_val = abs(U[r, s])
                    max_row, max_col = r, s

        # Intercambiar filas si es necesario
        if max_row != i:
            U[[i, max_row], :] = U[[max_row, i], :] # el corchete dentro de la posición de las filas sirve como multiasignación así no creamos variables de apoyo
            P[[i, max_row], :] = P[[max_row, i], :]
            if i > 0: # tenemos que solo se intercambia después de la primera interación por justamente en la primer vuelta no hemos calculado nada y sigue siendo la identidad solo intercambiariamos ceros identicos
                L[[i, max_row], :i] = L[[max_row, i], :i] # sin embargo para la segunda vuelta ya habremos calculado por lo menos un elemento que no esta en la diagonal de la columna 1, entonces ya es necesario intercambiar
                                                          # y solo intercambiamos hasta antes de la columna i, pues solo nos interesan la parte triangular inferior, la diagonal son unos por definición


        # Intercambio de columnas si es necesario
        if max_col != i:
            U[:, [i, max_col]] = U[:, [max_col, i]]
            Q[:, [i, max_col]] = Q[:, [max_col, i]]
            # Ahora vemos que no intercambiamos las columnas de L en ninguna ocasión porque L guarda en la parte triangular inferior todos los pivotes correspondientes a cada fila para la eliminación de los terminos debajo de la diagonal
            # sin embargo ahora los renglones no se movieron y el pivote de eliminación sigue correspondiendo a esa misma fila, tampoco debemos tener cuidado en el cambio de orden de las variables
            # pues el pivote afecta a toda la fila por igual no importa en que orden se encuentre y el cambio en U no afecta en nada

        # Eliminación gaussiana
        for j in range(i+1, n):
            L[j, i] = U[j, i] / U[i, i]
            U[j, :] = U[j, :] - (L[j, i] * U[i, :])

    return P, L, U, Q